simonbengtsson/jsPDF-AutoTable

README.md

Since I'll be deprecating `chipcastledotcom:jspdf-autotable` from Atmosphere, I wanted to update the docs so we don't have any more users installing it.
My only concern is that installing this new package from Atmosphere shows version `1.3.0` as the latest, yet it appears from your tags that you're currently at `1.3.2`:
```
jspdf:autotable  1.3.0  jsPDF-AutoTable (official): generate PDF tables on the client-side (jspdf:core plugin)
```
I'll loop in @splendido to see if there's anything we need to do to get this updating properly.
Thanks!

Update README for meteor package installation

---

jspdf.plugin.autotable.js

2 Changes: 
- Don't add a new page after output of last table row reaches end of page.
- rowHeight calculation of header rows didn't work correctly for bold text

Avoid unnecessary new page and rowHeight calculation fix

---

jspdf.plugin.autotable.js

Avoid isolated table headers during a page break when drawing multiple tables. This happens when the table header still fits on the current page, but the first row of table data starts on the next page.

Avoid isolated table headers during a page break

---

src/main.js

Calling autoTableEndPosY() without an existing table fails gracefully (it returns 0). The console error message is misleading (it's not really an error) and unnecessary.

Remove superfluous console logging

---

dist/jspdf.plugin.autotable.src.js

With some complex tables, the ```tableElem.rows``` property would return an empty ```<HtmlCollection>``` in Internet Explorer. Gathering the first ```<tr>``` skirts the issue. No issues in Chrome, FF, IE.

Gather header elements using getElementsByTagName to circumvent IE issues

---

src/widthCalculator.ts

Fixes #334 Overflow 'linebreak' should use scaleFactor() when adding on pt for rounding error for v3 branch. Contributes towards support for other units (such as inches).

Fix #334 in v3 to calculate linebreaks for other units.

---

src/calculator.ts

Fixes #334 Overflow 'linebreak' should use scaleFactor() when adding on pt for rounding error for the current release. Contributes towards support for other units (such as inches).

Fix #334 in v2 to calculate linebreaks for other units.

---

dist/index.d.ts
examples/typescript/index.ts
src/interfaces.ts

- `columnStyles` should be dictionary of styles rather than a single style
- Support using auto table with `columns`, in which case body would be array of objects instead of array of arrays
- Updated typescript example to use `import` instead of require

Typing improvements

---

src/tableDrawer.ts

try fixing #469 Row Content is NOT properly wrapped to corresponding cells in last rows (on few pages) and cutoff on next page.
I am not sure if I understand the issue correctly(especially the 'last row not wrapped correctly' part in description ), but the cutoff issue seems to be solved in this fix.

 try fixing #469 

---

src/inputParser.ts

When `columns` is not specified and a row value is `undefined` the parser would attempt `undefined.colSpan` resulting in a `Cannot read property 'colSpan' of undefined`

Don't attempt to access colSpan from undefined row values

---

src/common.ts

Fixes #564
[Math.max](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/max) can take more than two parameters, so using it with `Array.prototype.reduce` if the form `array.reduce(Math.max, 0)` with an array of two or more elements will result in a value of `NaN` because `reduce` will pass 4 parameters with the last one being the source array, for arrays with one element the last parameter will be the element itself (which is strange) so it won't cause a problem because the element is a number.

Fix Math.max with Array reduce

---

src/widthCalculator.ts

Fixes #566 
The problem :
when calculating columns widths, if `suggestedWidth` < `column.minWidth`, we remove `column` from the array and subtract `column.wrappedWidth` from `wrappedAutoColumnsWidth`, but we don't take in consideration the change in `diffWidth` which is based on how wide ALL columns (wrapped) compared to the `tableWidth`.
The fix :
we use `availableSpace` which get updated every time we remove a `column` from the calculation. then we calculated `diffWidth` based on that.

Fix tableWidth bug with minCellWidth (availableSpace)

---

src/HookData.ts

fix the following typescript transpile error:
```
14:46 Property 'margin' does not exist on type '{}'.
14 |             doc.text('Report', data.settings.margin.left, 18);
```

hookdata settings type to any

---

examples/examples.js

The previous link is broken. Also added the reference to jsPDF for those who don't know how to add fonts in jsPDF.

Updated font-converter link. Added ref to jsPDF's font instructions

---

dist/index.d.ts
dist/jspdf.plugin.autotable.js
dist/jspdf.plugin.autotable.min.js
src/cssParser.ts

I replaced style.padding with an array of the 4 paddingTop, right, bottom, left.
As the combined padding in getComputedStyle is only supported in chrome.

Fix for padding not being applied in Firefox when using the useCss option

---

src/common.ts
src/widthCalculator.ts

Fixes #598
Apply font-only styles for text size calculations when calling `applyStyles()`.
When the dataset is large, `applyStyles` gets called large number of times on the first page for text calculations before drawing any cells, this causes the first page to be blank when `compress` option is `true` because of a bug in `jsPDF` v1.5.3.
To reduce the effect of this bug, we only apply font styles in this calculations (we only need font styles for it anyway).
Also apparently, either color styles is the ones that cause this bug or it has a much bigger effect  than font styles.
Before the fix, the bug happens for any table has more than 63k cells (~21k rows × 3 columns)
After the fix, I couldn't reach the limit when the bug happens, for a table with 1.5m cells (~500k rows × 3 columns) every …

Apply font-only styles for calculations

---

src/tableDrawer.ts

Fixes #623 
Currently, halign: 'center' and valign: 'middle' centers the text absolutely regardless of the padding which is wrong, html takes padding into account and centers relative to the net size after the padding.
This PR fixes that to align with html behavior, here's the before & after :
Before :
After :
Here's the test setup file used :
[padding-align.zip](https://github.com/simonbengtsson/jsPDF-AutoTable/files/4461766/padding-align.zip)
_(extract in `examples/local`)_

Fix cell align with padding

---

src/common.ts

Fixes #632 
Bug introduced in version 3.4.1 where order of lines was changed
setFontStyle() should be called before setFont()

Fix setFont() called before setFontStyle()

---

webpack.config.js

"this" is undefined when using async module imports, but window is not

Use window as global object if this is undefined

---

src/tableDrawer.ts

Last page row breaking is not working properly in the last lib version because last row height is not recalculated. (Cell rect height is incorrect as the result).
See the example of generated document:
This behavior appeared after refactoring in this [commit](https://github.com/simonbengtsson/jsPDF-AutoTable/commit/87a5bd0954f7bb81e65fcb43adc81b1596c5705a#diff-031c1dcfc6d72fe46c173a047b1f9401L84).
(The height of breaking line must be reset so that it is recalculated below in the code with new corrected value).
---------------------------------------------
P.S. I also noticed that the [_Row.spansMultiplePages_ property](https://github.com/simonbengtsson/jsPDF-AutoTable/blob/master/src/models.ts#L164) is not used anymore.
---------------------------------------------
Thanks a lot for this …

Fixed last row height recalculation in case of row is broken to next page

---

src/config.ts

Hello,
Thank you very much for this awesome library. The library is working very well in our projects. Recently we need to import some custom fontStyle to our project and found that the typing do not allow it. Hold that you can accept this patch to help us unblock the situation.

fix: fontStyle should accept custom font value

---

src/htmlParser.ts

* Fix of #757 
* Now supports `<br> `, `<br />` , `<br customAttr="">` or any other things like `id` `class` inside `<br>` tag. it is  useful when working with angular or react

Fix new line issue when using in angular #757

---

src/tablePrinter.ts

`calculateAllColumnsCanFitInPage` function rely on returned fitted columns from `getColumnsCanFitInPage` to update `start` index.
https://github.com/simonbengtsson/jsPDF-AutoTable/blob/
let's say we have columns `[0, 1, 2, 3, 4] `and we want to repeat column `0` on every page
assume only columns` 0 and 1` fit to first page then `start=2`
if columns `0 and 2` could be fitted to second page then `start=4`
in the next iteration column `3` will be skipped!
Solution: rely on last returned index from `getColumnsCanFitInPage`

Fix skipping columns for horizontalPageBreakRepeat

---

README.md

See https://github.com/simonbengtsson/jsPDF-AutoTable/issues/857
This change switches the default method of import from 
```
import 'jspdf-autotable';
```
to
```
import autoTable from 'jspdf-autotable';
```
The change is also made in the examples in the readme. I am not entirly sure if 'plugin' is the right word in (new) line 47.

change default import method in documentation

---

webpack.config.js

Fix #871.
Just in case, I've added more safeguards in case the environment doesn't support the current global this.

feat: update global object webpack

---

src/main.ts

I know it's not that critical, but when I was looking at the codebase, I saw this unused imported variable.

Remove unused imported variable

---

src/documentHandler.ts
src/tableDrawer.ts

fix: revert the draw color and line width after drawing the table

---

src/tableDrawer.ts

Fixes https://github.com/simonbengtsson/jsPDF-AutoTable/issues/942
I came to this conclusion by stepping through with a debugger and noticed that the header row on subsequent pages has its styles applied (e.g. `textColor: 255`) but then is never reset for the body rows.
The first page rows doesn't have this problem because there is a `doc.applyStyles(doc.userStyles)` between the `printRow` of the first header and the first body row.
https://github.com/simonbengtsson/jsPDF-AutoTable/blob/f3d4de7172c4d71c1f801e4cae21fca464bb5ac6/src/tableDrawer.ts#L49-L62
It made sense for me to always reset the doc styles after the header row is inserted.

Reset doc styles after new page header is printed

---

package.json

When using the `NodeNext` resolver the `types` field is ignored. Instead, the types should be defined under the `exports` field.

Fix resolution of types when using ModuleResolution: "NodeNext" in tsconfig

---

examples/examples.js
index.html
src/documentHandler.ts
src/tableDrawer.ts

Completely reworked the way the border drawing works. It now takes into consideration the neighbouring borders to achieve 'sharp' edge. Borders are still centered on cell edge.
If `lineWidth: number` is provided, borders will be drawn using rectangle with stroke.
If `lineWidth: Partial<LineWidth>` is provided, borders will be drawn individually.
The tests passed, and from what I could see, all examples are working. I've also added example page with borders showcase - it may not be beautiful but showcases what can be done with the borders now.
Closes #897

Prevent lineWidth object from filling the cell in black [#897]

---

README.md
examples/examples.js
src/config.ts
src/inputParser.ts
src/models.ts
src/tableDrawer.ts

Adds a `willDrawPage` hook. This makes it possible to add a page header _before_ content is added, which lets you avoid text selection like this:
https://github.com/simonbengtsson/jsPDF-AutoTable/assets/11315492/444bb5e0-83e8-4305-8d97-4924e2a702aa
1. The `callEndPageHooks` function calls `doc.applyStyles(doc.userStyles)` before running the handlers. I don't know whether that would also be needed in `callWillDrawPageHooks`
2. I don't think the hook runs for the deprecated `autoTableAddPage()`

Add `willDrawPage` hook

---

src/tableDrawer.ts

Prevents header and footer heights to be included twice 
Fixes #976

Use `body` instead of `allRows()` for `pageBreak: 'avoid'

---

examples/examples.js
src/documentHandler.ts
src/tableDrawer.ts

Fixes https://github.com/simonbengtsson/jsPDF-AutoTable/issues/966

Fix #966 - hex fillColor together with lineWidth causes invalid arguments for rect fn

---

src/config.ts
src/models.ts
src/tablePrinter.ts

Hi. I have added a feature to support repeating multiple columns using the `horizontalPageBreakRepat` option. It accepts now `string[] | number[] | string | number` type which **DOESN'T** make any breaking changes.
After a positive review, I will add a new example to `examples.js` file.
Please let me know if you have any suggestions or questions.
Fixes #911

Add support for repeating multiple columns using horizontalPageBreakRepeat

---

src/autoTableText.ts
src/config.ts
src/documentHandler.ts
src/models.ts
src/tableDrawer.ts
src/widthCalculator.ts

Fixes #767, #712, #753, #887, #802, #906
Reference PR : #754
```js
const doc = new jsPDF();
table(10, 'LineHeightFactor: 1.15 \n(default)')
doc.setLineHeightFactor(0.9)
table(80, 'LineHeightFactor: 0.9')
doc.setLineHeightFactor(2.5)
table(150, 'LineHeightFactor: 2.5')
function table(x, title) {
doc.text(title, x, 40)
doc.autoTable({
body: [
['text\non\nfour\nlines'],
['text on one line'],
['text on one line'],
],
theme: 'grid',
tableWidth: 50,
startY: 50,
styles: {
textColor: 'black',
fontSize: 18,
lineColor: 0,
// cellPadding: 0,
},
margin: {left: x}
})
}
```

Add support for lineHeightFactor

---

src/documentHandler.ts
src/tableDrawer.ts

Fixes #1001
Refs : #730, #961, #978
`fillColor: null` caused cells to have full borders even when `lineWidth` is an object with partial borders.
This is caused by calling `rect()` to draw the background with `null` as `fillStyle` when `fillColor` is null :
https://github.com/simonbengtsson/jsPDF-AutoTable/blob/4c04f6a089b9dea919e84fee5fff649552cd49b8/src/tableDrawer.ts#L409-L410
```js
doc.autoTable({
head: [['Name', 'Email', 'Country']],
body: [
['David', 'david@example.com', 'Sweden'],
['Castille', 'castille@example.com', 'Spain'],
],
theme: 'plain',
styles: {
// fillColor: null,
lineColor: 0,
lineWidth: {top: 0, bottom: 0.3, right: 0, left: 0},
},
})
```

Fix lineWidth object bug with fillColor: null

---

src/cssParser.ts
test/testCssParser.ts

Fixes #915
Individual borders sides (`lineWidth` as an object) was introduced in #730 but support was never added to the css parser so only `borderTopWidth` was used to set `lineWidth` as a number, this PR adds the missing support.
---
<details><summary>Example code (border-bottom)</summary>
```html
<!doctype html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>Test PDF</title>
<style>
body {
margin: 0;
display: flex;
flex-direction: column;
height: 100vh;
}
#output {
width: 100%;
flex-grow: 1;
}
table {
border-collapse: collapse;
margin: 10px 60px;
}
td, th {
text-align: center;
border-bottom: solid 1px red;
}
</style>
</head>
<body>
<table id="table">
<thead>
<th>Name</th>
<th>Email</th>
<th>Country</th> …
```

Support css parsing of individual borders sides

---

src/applyPlugin.ts
test/testHtmlParser.ts

Handle tables without thead gracefully

---

README.md
examples/examples.js
src/documentHandler.ts
src/inputParser.ts
src/inputValidator.ts
src/models.ts
src/tableDrawer.ts
src/widthCalculator.ts

Hooks internally were arrays to combine hooks from options & globalDefaults, with the removal of globalDefaults, no need to keep then in arrays.

[v4] Remove globalDefaults

---

README.md
examples/examples.js
index.html
src/common.ts
src/config.ts
src/models.ts
src/tableCalculator.ts
src/tablePrinter.ts
src/widthCalculator.ts
test/testInputParser.ts
test/testWidthCalculator.ts

Introducing new width options to give more dynamic control over the column widths
**Old options:**
```ts
cellWidth: 'auto' | 'wrap' | number
minCellWidth: number
---
tableWidth: 'auto' | 'wrap' | number
```
**New options:**
```ts
cellWidth: 'auto' | 'min-content' | 'max-content' | number
minCellWidth: 'auto' | 'min-content' | 'max-content' | number
maxCellWidth: 'auto' | 'min-content' | 'max-content' | number
---
tableWidth: 'auto' | 'min-content' | 'max-content' | 'fit-content' | number
```
[min-content](https://developer.mozilla.org/en-US/docs/Web/CSS/min-content) : The minimum width required to fit the content in a readable manner (with no word-breaking).
[max-content](https://developer.mozilla.org/en-US/docs/Web/CSS/max-content) : The full-width required to fit the content without …

Rewrite width options and distribution algorithm
